package: nbextensions

platform: 
 - linux-64

engine:
 - python=3.5
 - python=3.4


script:
  - conda build .

after_success:
   - conda convert -p all /opt/miniconda/conda-bld/linux-64/nbextensions-*.tar.bz2 -o /opt/miniconda/conda-bld

after_failure:
   - echo "Build failed!"

build_targets:
   - /opt/miniconda/conda-bld/*/*.tar.bz2
