package:
    name: nbextensions
    version: "master"

source:
    git_url: https://github.com/ipython-contrib/IPython-notebook-extensions

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    script: python setup.py install
  
requirements:
  build:
    - jupyter
    - ipython >=4
    - python
    - psutil >=2.2.1
    - pyyaml

  run:
    - jupyter
    - ipython >=4
    - python
    - psutil >=2.2.1
    - pyyaml


about:
  home: https://github.com/ipython-contrib/IPython-notebook-extensions
  license:  Modified BSD License
  summary: 'Notebook extensions for the Jupyter/IPython notebook'

